title: North Carolina Modeling Infectious Diseases Project (NC MInD)
description: Agent-based modeling of COVID-19, healthcare system capacity, and healthcare-associated infections

theme: jekyll-theme-slate

show_downloads: false
github:
  is_project_page: false