title: North Carolina Modeling Infectious Diseases Project (NC MInD)
description: Agent-based modeling for COVID-19, healthcare system capacity, and healthcare-associated infections

theme: jekyll-theme-slate
